### ISSUE TITLE
i get the error   'ReplicationMiddleware' object is not callable

### ISSUE THREAD

**Issue by popsonebz** [yandex/django_replicated#34]
i am using two databases, one as master and the other as slave but i get this error.

'ReplicationMiddleware' object is not callable

**Comment by gmorell** [comment]
I'm just chiming in to say this is also happening for me and I believe it's caused by the changes to django's middleware classes in 1.10. Moving from MIDDLEWARE_CLASSES declaration to the MIDDLEWARE declaration changed some structural things about them. There is more information here on how to make versions that support both old and new versions.

https://docs.djangoproject.com/en/1.11/topics/http/middleware/#upgrading-middleware

**Comment by daevaorn** [comment]
Thanks.

Fixed with https://github.com/yandex/django_replicated/commit/961475e41723dcd902f140f97fadeaca5a404a9f
